- name: Deploy Web server
  hosts: servers
  tasks:
    - name: Ping
      ping:
    - name: Install Dependencies
      apt: name {{item}} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb

    - name: include db tasks
      include_tasks:
        file: tasks/db.yml

    - name: include Web tasks
      include_tasks:
        file: tasks/web.yml
