---
# tasks file for mysql_db
- name: Install MySql
  apt: name {{item}} state=present
  with_items:
    - mysql-server
    - mysql-client
    - python3-PyMySQL
    - python3-mysqldb

- name: Start service mysql, if not started
  systemd:
    name: mysql
    state: started
    enabled: yes
    daemon_reload: yes

- name: Create MySql Database
  mysql_db:
    name: "{{db_name}}"
    state: present

- name: Create database User
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_password}}"
    priv: "*.*:ALL"
    state: present
    host: "%"